version: '3.9'

services:
  db:
    build:
      context: .
    container_name: tienda-perritos-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: tienda_perritos
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
    driver: local
